package io.safebump.core.report;

import io.safebump.core.analysis.AnalysisIssue;
import io.safebump.core.analysis.ProjectAnalysis;
import io.safebump.core.upgrade.DependencyEdge;
import io.safebump.core.upgrade.DependencyGraphDiff;
import io.safebump.core.upgrade.PackageChange;
import io.safebump.core.upgrade.PackageChangeType;
import io.safebump.core.upgrade.UpgradeAnalysis;

import java.util.Objects;

/** Formats an upgrade analysis as a stable GitHub-flavoured Markdown report. */
public final class PullRequestReportFormatter {

    public static final String COMMENT_MARKER = "<!-- safebump-dependency-analysis -->";

    public String format(UpgradeAnalysis analysis) {
        Objects.requireNonNull(analysis, "analysis");
        DependencyGraphDiff diff = analysis.diff();
        StringBuilder report = new StringBuilder();

        report.append(COMMENT_MARKER).append('\n')
                .append("## SafeBump dependency analysis\n\n")
                .append("**Ecosystem:** `")
                .append(escapeCode(analysis.before().ecosystem()))
                .append("`\n\n")
                .append(summarySentence(diff)).append("\n\n")
                .append("| Metric | Result |\n")
                .append("| --- | ---: |\n")
                .append("| Packages changed | ").append(diff.changedPackages().size()).append(" |\n")
                .append("| Upgraded | ").append(count(diff, PackageChangeType.UPGRADED)).append(" |\n")
                .append("| Downgraded | ").append(count(diff, PackageChangeType.DOWNGRADED)).append(" |\n")
                .append("| Added | ").append(count(diff, PackageChangeType.ADDED)).append(" |\n")
                .append("| Removed | ").append(count(diff, PackageChangeType.REMOVED)).append(" |\n")
                .append("| Transitive changes | ").append(diff.transitiveChanges().size()).append(" |\n")
                .append("| Dependency edges added | ").append(diff.addedEdges().size()).append(" |\n")
                .append("| Dependency edges removed | ").append(diff.removedEdges().size()).append(" |\n");

        appendPackageChanges(report, diff);
        appendEdgeChanges(report, diff);
        appendMetadataIssues(report, analysis);

        report.append("\n<sub>Generated by SafeBump. This report describes resolved dependency changes; "
                + "it does not replace the project's test suite.</sub>\n");
        return report.toString();
    }

    private static String summarySentence(DependencyGraphDiff diff) {
        if (diff.isEmpty()) {
            return "✅ No resolved package or dependency-edge changes were detected.";
        }
        return "ℹ️ This update changes **" + diff.changedPackages().size()
                + " package(s)** and **"
                + (diff.addedEdges().size() + diff.removedEdges().size())
                + " dependency edge(s)**.";
    }

    private static int count(DependencyGraphDiff diff, PackageChangeType type) {
        return diff.changesOfType(type).size();
    }

    private static void appendPackageChanges(
            StringBuilder report,
            DependencyGraphDiff diff) {
        if (diff.changedPackages().isEmpty()) {
            return;
        }

        report.append("\n### Package changes\n\n")
                .append("| Package | Change | Version | Scope |\n")
                .append("| --- | --- | --- | --- |\n");
        for (PackageChange change : diff.changedPackages()) {
            report.append("| `").append(escapeCode(change.packageName())).append("` | ")
                    .append(displayType(change.type())).append(" | ")
                    .append(formatVersion(change)).append(" | ")
                    .append(change.isTransitive() ? "Transitive" : "Direct")
                    .append(" |\n");
        }
    }

    private static void appendEdgeChanges(
            StringBuilder report,
            DependencyGraphDiff diff) {
        if (diff.addedEdges().isEmpty() && diff.removedEdges().isEmpty()) {
            return;
        }

        report.append("\n<details>\n<summary>Dependency-edge changes</summary>\n\n");
        appendEdges(report, "Added", "+", diff.addedEdges());
        appendEdges(report, "Removed", "-", diff.removedEdges());
        report.append("</details>\n");
    }

    private static void appendEdges(
            StringBuilder report,
            String heading,
            String prefix,
            java.util.List<DependencyEdge> edges) {
        if (edges.isEmpty()) {
            return;
        }
        report.append("**").append(heading).append("**\n\n```text\n");
        for (DependencyEdge edge : edges) {
            report.append(prefix).append(' ').append(edge).append('\n');
        }
        report.append("```\n\n");
    }

    private static void appendMetadataIssues(
            StringBuilder report,
            UpgradeAnalysis analysis) {
        if (analysis.before().isConsistent() && analysis.after().isConsistent()) {
            return;
        }

        report.append("\n### Metadata warnings\n\n");
        appendIssues(report, "Before", analysis.before());
        appendIssues(report, "After", analysis.after());
    }

    private static void appendIssues(
            StringBuilder report,
            String label,
            ProjectAnalysis analysis) {
        for (AnalysisIssue issue : analysis.issues()) {
            report.append("- **").append(label).append(" — ")
                    .append(escapeText(issue.code())).append(":** ")
                    .append(escapeText(issue.message())).append('\n');
        }
    }

    private static String formatVersion(PackageChange change) {
        return switch (change.type()) {
            case ADDED -> "— → `" + escapeCode(
                    change.after().orElseThrow().packageVersion().version()) + "`";
            case REMOVED -> "`" + escapeCode(
                    change.before().orElseThrow().packageVersion().version()) + "` → —";
            case UPGRADED, DOWNGRADED -> "`" + escapeCode(
                    change.before().orElseThrow().packageVersion().version())
                    + "` → `" + escapeCode(
                    change.after().orElseThrow().packageVersion().version()) + "`";
            case UNCHANGED -> "Unchanged";
        };
    }

    private static String displayType(PackageChangeType type) {
        return type.name().charAt(0) + type.name().substring(1).toLowerCase(java.util.Locale.ROOT);
    }

    private static String escapeCode(String value) {
        return value.replace("`", "\\`");
    }

    private static String escapeText(String value) {
        return value.replace("\\", "\\\\")
                .replace("*", "\\*")
                .replace("_", "\\_")
                .replace("<", "&lt;")
                .replace(">", "&gt;");
    }
}
